[project]
name = "smartedu-backend"
version = "0.1.0"
description = "Backend for SmartEdu Agent"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "requests",
    "python-dotenv",
    "pydantic"
]
